[project]
name = "RDPSessionBot"
version = "0.1.5"
description = "Python telegram rdp session restart bot with some benefits"
requires-python = ">=3.10"
dependencies = [
    "paramiko>=3.5.1",
    "python-dotenv==1.1.1",
    "python-telegram-bot>=22.3",
]
